version: "3.8"

services:
  web:
    build: ./web
    container_name: my_web
    expose:
      - "5000"
    depends_on:
      - redis
    networks:
      - app_net
    volumes:
      - ./web:/app

  redis:
    image: redis:alpine
    container_name: my_redis
    volumes:
      - redis_data:/data
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app_net

networks:
  app_net:

volumes:
  redis_data:

