name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-flask-app ./web

      - name: Run container and test
        run: |
          docker run -d -p 5000:5000 --name test_app my-flask-app
          sleep 5
          curl -f http://localhost:5000 || (docker logs test_app && exit 1)
